Added support for tls cipher suites

diff --git a/modules/run-vault/run-vault b/modules/run-vault/run-vault
--- a/modules/run-vault/run-vault
+++ b/modules/run-vault/run-vault
@@ -19,7 +19,7 @@ readonly EC2_INSTANCE_METADATA_URL="http://169.254.169.254/latest/meta-data"
 readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 readonly SCRIPT_NAME="$(basename "$0")"
 
-function print_usage {
+function print_usage() {
   echo
   echo "Usage: run-vault [OPTIONS]"
   echo
@@ -29,6 +29,7 @@ function print_usage {
   echo
   echo -e "  --tls-cert-file\tSpecifies the path to the certificate for TLS. Required. To use a CA certificate, concatenate the primary certificate and the CA certificate together."
   echo -e "  --tls-key-file\tSpecifies the path to the private key for the certificate. Required."
+  echo -e "  --tls-cipher-suites\tSpecifies the list of supported ciphersuites as a comma-separated-list. The list of all available ciphersuites is available at https://golang.org/src/crypto/tls/cipher_suites.go"
   echo -e "  --port\t\tThe port for Vault to listen on. Optional. Default is $DEFAULT_PORT."
   echo -e "  --cluster-port\tThe port for Vault to listen on for server-to-server requests. Optional. Default is --port + 1."
   echo -e "  --api-addr\t\tThe full address to use for Client Redirection when running Vault in HA mode. Defaults to \"https://[instance_ip]:$DEFAULT_PORT\". Optional."
@@ -72,36 +73,36 @@ function print_usage {
   echo "  run-vault --tls-cert-file /opt/vault/tls/vault.crt.pem --tls-key-file /opt/vault/tls/vault.key.pem --enable-s3-backend --s3-bucket my-vault-bucket --s3-bucket-region us-east-1"
 }
 
-function log {
+function log() {
   local -r level="$1"
   local -r message="$2"
   local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
+  echo >&2 -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
 }
 
-function log_info {
+function log_info() {
   local -r message="$1"
   log "INFO" "$message"
 }
 
-function log_warn {
+function log_warn() {
   local -r message="$1"
   log "WARN" "$message"
 }
 
-function log_error {
+function log_error() {
   local -r message="$1"
   log "ERROR" "$message"
 }
 
 # Based on code from: http://stackoverflow.com/a/16623897/483528
-function strip_prefix {
+function strip_prefix() {
   local -r str="$1"
   local -r prefix="$2"
   echo "${str#$prefix}"
 }
 
-function assert_not_empty {
+function assert_not_empty() {
   local -r arg_name="$1"
   local -r arg_value="$2"
 
@@ -112,16 +113,16 @@ function assert_not_empty {
   fi
 }
 
-function lookup_path_in_instance_metadata {
+function lookup_path_in_instance_metadata() {
   local -r path="$1"
   curl --silent --location "$EC2_INSTANCE_METADATA_URL/$path/"
 }
 
-function get_instance_ip_address {
+function get_instance_ip_address() {
   lookup_path_in_instance_metadata "local-ipv4"
 }
 
-function assert_is_installed {
+function assert_is_installed() {
   local -r name="$1"
 
   if [[ ! $(command -v ${name}) ]]; then
@@ -130,29 +131,28 @@ function assert_is_installed {
   fi
 }
 
-function get_vault_version {
+function get_vault_version() {
   #Runs vault -v to get the vault version, then strips out everything but the version number.
   #The current output format of vault -v is:
   #Vault v0.10.4 ('e21712a687889de1125e0a12a980420b1a4f72d3')
-  /usr/local/bin/vault -v|awk '{print $2}'|tr -d v
+  /usr/local/bin/vault -v | awk '{print $2}' | tr -d v
 }
 
-function vault_version_at_least {
+function vault_version_at_least() {
   local -r config_path=$1
   local -r ui_config=$2
   VAULT_VERSION=$(get_vault_version)
 
   #This if statement will echo the current vault version and the minimum version required for ui support.
   #It then strips out the comments, sorts the two values, and chooses the top (least) one.
-  if [[ $(echo "$VAULT_VERSION 0.10.0" | tr " " "\n" |sort --version-sort| head -n 1) = 0.10.0 ]]
-    then
-      echo -e "$ui_config" >> "$config_path"
-    else
-      log_info "Vault 0.10.0 or greater is required for UI support."
+  if [[ $(echo "$VAULT_VERSION 0.10.0" | tr " " "\n" | sort --version-sort | head -n 1) = 0.10.0 ]]; then
+    echo -e "$ui_config" >>"$config_path"
+  else
+    log_info "Vault 0.10.0 or greater is required for UI support."
   fi
 }
 
-function generate_vault_agent_config {
+function generate_vault_agent_config() {
   local -r config_dir="$1"
   local -r data_dir="$2"
   local -r vault_address="$3"
@@ -172,31 +172,35 @@ function generate_vault_agent_config {
 
   local ca_cert_config=""
   if [[ ! -z $ca_cert_file ]]; then
-   ca_cert_config=$(cat <<EOF
+    ca_cert_config=$(
+      cat <<EOF
   ca_cert = "$ca_cert_file"\n
 EOF
-)
+    )
   fi
 
   local client_cert_config=""
   if [[ ! -z $client_cert_file ]] && [[ ! -z $client_key_file ]]; then
-   client_cert_config=$(cat <<EOF
+    client_cert_config=$(
+      cat <<EOF
   client_cert = "$client_cert_file"
   client_key = "$client_key_file"\n
 EOF
-)
+    )
   fi
 
-  local -r vault_config=$(cat <<EOF
+  local -r vault_config=$(
+    cat <<EOF
 vault {
   address = "https://$vault_address:$vault_port"
 $ca_cert_config
 $client_cert_config
 }\n
 EOF
-)
+  )
 
-  local -r auto_auth_config=$(cat <<EOF
+  local -r auto_auth_config=$(
+    cat <<EOF
 auto_auth {
   method "aws" {
     mount_path = "$auth_mount_path"
@@ -213,15 +217,15 @@ auto_auth {
   }
 }\n
 EOF
-)
-  echo -e "$pid_config" > "$config_path"
-  echo -e "$vault_config" >> "$config_path"
-  echo -e "$auto_auth_config" >> "$config_path"
+  )
+  echo -e "$pid_config" >"$config_path"
+  echo -e "$vault_config" >>"$config_path"
+  echo -e "$auto_auth_config" >>"$config_path"
 
   chown "$user:$user" "$config_path"
 }
 
-function generate_vault_config {
+function generate_vault_config() {
   local -r tls_cert_file="$1"
   local -r tls_key_file="$2"
   local -r port="$3"
@@ -237,6 +241,7 @@ function generate_vault_config {
   local -r auto_unseal_kms_key_id="${13}"
   local -r auto_unseal_kms_key_region="${14}"
   local -r auto_unseal_endpoint="${15}"
+  local -r tls_cipher_suites="${16}"
   local -r config_path="$config_dir/$VAULT_CONFIG_FILE"
 
   local instance_ip_address
@@ -250,48 +255,54 @@ function generate_vault_config {
       endpoint="endpoint   = \"$auto_unseal_endpoint\""
     fi
 
-    auto_unseal_config=$(cat <<EOF
+    auto_unseal_config=$(
+      cat <<EOF
 seal "awskms" {
   kms_key_id = "$auto_unseal_kms_key_id"
   region     = "$auto_unseal_kms_key_region"
   $endpoint
 }\n
 EOF
-)
+    )
   fi
 
   log_info "Creating default Vault config file in $config_path"
-  local -r ui_config=$(cat <<EOF
+  local -r ui_config=$(
+    cat <<EOF
 ui = true
 
 EOF
-)
+  )
 
-  local -r listener_config=$(cat <<EOF
+  local -r listener_config=$(
+    cat <<EOF
 listener "tcp" {
-  address         = "0.0.0.0:$port"
-  cluster_address = "0.0.0.0:$cluster_port"
-  tls_cert_file   = "$tls_cert_file"
-  tls_key_file    = "$tls_key_file"
+  address           = "0.0.0.0:$port"
+  cluster_address   = "0.0.0.0:$cluster_port"
+  tls_cert_file     = "$tls_cert_file"
+  tls_key_file      = "$tls_key_file"
+  tls_cipher_suites = "$tls_cipher_suites"
 }\n
 EOF
-)
+  )
 
   local consul_storage_type="storage"
   local s3_config=""
   if [[ "$enable_s3_backend" == "true" ]]; then
-    s3_config=$(cat <<EOF
+    s3_config=$(
+      cat <<EOF
 storage "s3" {
   bucket = "$s3_bucket"
   path   = "$s3_bucket_path"
   region = "$s3_bucket_region"
 }\n
 EOF
-)
+    )
     consul_storage_type="ha_storage"
   fi
 
-  local -r consul_storage=$(cat <<EOF
+  local -r consul_storage=$(
+    cat <<EOF
 $consul_storage_type "consul" {
   address = "127.0.0.1:8500"
   path    = "vault/"
@@ -304,19 +315,19 @@ cluster_addr  = "https://$instance_ip_address:$cluster_port"
 api_addr      = "$api_addr"
 
 EOF
-)
+  )
 
   vault_version_at_least "$config_path" "$ui_config"
 
-  echo -e "$auto_unseal_config" >> "$config_path"
-  echo -e "$listener_config" >> "$config_path"
-  echo -e "$s3_config" >> "$config_path"
-  echo -e "$consul_storage" >> "$config_path"
+  echo -e "$auto_unseal_config" >>"$config_path"
+  echo -e "$listener_config" >>"$config_path"
+  echo -e "$s3_config" >>"$config_path"
+  echo -e "$consul_storage" >>"$config_path"
 
   chown "$user:$user" "$config_path"
 }
 
-function generate_systemd_config {
+function generate_systemd_config() {
   local -r systemd_config_path="$1"
   local -r vault_config_dir="$2"
   local -r vault_bin_dir="$3"
@@ -329,7 +340,7 @@ function generate_systemd_config {
 
   local vault_description="HashiCorp Vault - A tool for managing secrets"
   local vault_command="server"
-  local vault_config_file_or_dir="$vault_config_dir"  # Vault agent requires single file, but server can accept config dir.
+  local vault_config_file_or_dir="$vault_config_dir" # Vault agent requires single file, but server can accept config dir.
   if [[ "$is_vault_agent" == "true" ]]; then
     vault_command="agent"
     vault_description="HashiCorp Vault Agent"
@@ -338,7 +349,8 @@ function generate_systemd_config {
 
   log_info "Creating systemd config file to run Vault in $systemd_config_path"
 
-  local -r unit_config=$(cat <<EOF
+  local -r unit_config=$(
+    cat <<EOF
 [Unit]
 Description=\"$vault_description\"
 Documentation=https://www.vaultproject.io/docs/
@@ -347,9 +359,10 @@ After=network-online.target
 ConditionFileNotEmpty=$config_path
 
 EOF
-)
+  )
 
-  local -r service_config=$(cat <<EOF
+  local -r service_config=$(
+    cat <<EOF
 [Service]
 User=$vault_user
 Group=$vault_user
@@ -373,7 +386,7 @@ StartLimitIntervalSec=60
 StartLimitBurst=3
 LimitNOFILE=65536
 EOF
-)
+  )
 
   local log_config=""
   if [[ ! -z $vault_systemd_stdout ]]; then
@@ -383,19 +396,20 @@ EOF
     log_config+="StandardError=$vault_systemd_stderr\n"
   fi
 
-  local -r install_config=$(cat <<EOF
+  local -r install_config=$(
+    cat <<EOF
 [Install]
 WantedBy=multi-user.target
 EOF
-)
+  )
 
-  echo -e "$unit_config" > "$systemd_config_path"
-  echo -e "$service_config" >> "$systemd_config_path"
-  echo -e "$log_config" >> "$systemd_config_path"
-  echo -e "$install_config" >> "$systemd_config_path"
+  echo -e "$unit_config" >"$systemd_config_path"
+  echo -e "$service_config" >>"$systemd_config_path"
+  echo -e "$log_config" >>"$systemd_config_path"
+  echo -e "$install_config" >>"$systemd_config_path"
 }
 
-function start_vault {
+function start_vault() {
   log_info "Reloading systemd config and starting Vault"
   sudo systemctl daemon-reload
   sudo systemctl enable vault.service
@@ -403,12 +417,12 @@ function start_vault {
 }
 
 # Based on: http://unix.stackexchange.com/a/7732/215969
-function get_owner_of_path {
+function get_owner_of_path() {
   local -r path="$1"
   ls -ld "$path" | awk '{print $3}'
 }
 
-function run {
+function run() {
   local tls_cert_file=""
   local tls_key_file=""
   local port="$DEFAULT_PORT"
@@ -438,148 +452,153 @@ function run {
   local auto_unseal_kms_key_id=""
   local auto_unseal_kms_key_region=""
   local auto_unseal_endpoint=""
+  local tls_cipher_suites=""
   local all_args=()
 
   while [[ $# > 0 ]]; do
     local key="$1"
 
     case "$key" in
-      --tls-cert-file)
-        tls_cert_file="$2"
-        shift
-        ;;
-      --tls-key-file)
-        tls_key_file="$2"
-        shift
-        ;;
-      --port)
-        assert_not_empty "$key" "$2"
-        port="$2"
-        shift
-        ;;
-      --cluster-port)
-        assert_not_empty "$key" "$2"
-        cluster_port="$2"
-        shift
-        ;;
-      --config-dir)
-        assert_not_empty "$key" "$2"
-        config_dir="$2"
-        shift
-        ;;
-       --api-addr)
-        assert_not_empty "$key" "$2"
-        api_addr="$2"
-        shift
-        ;;
-      --bin-dir)
-        assert_not_empty "$key" "$2"
-        bin_dir="$2"
-        shift
-        ;;
-      --log-level)
-        assert_not_empty "$key" "$2"
-        log_level="$2"
-        shift
-        ;;
-      --systemd-stdout)
-        assert_not_empty "$key" "$2"
-        systemd_stdout="$2"
-        shift
-        ;;
-      --systemd-stderr)
-        assert_not_empty "$key" "$2"
-        systemd_stderr="$2"
-        shift
-        ;;
-      --user)
-        assert_not_empty "$key" "$2"
-        user="$2"
-        shift
-        ;;
-      --skip-vault-config)
-        skip_vault_config="true"
-        ;;
-      --enable-s3-backend)
-        enable_s3_backend="true"
-        ;;
-      --s3-bucket)
-        s3_bucket="$2"
-        shift
-        ;;
-      --s3-bucket-path)
-        s3_bucket_path="$2"
-        shift
-        ;;
-      --s3-bucket-region)
-        s3_bucket_region="$2"
-        shift
-        ;;
-      --agent)
-        agent="true"
-        ;;
-      --agent-vault-address)
-        assert_not_empty "$key" "$2"
-        agent_vault_address="$2"
-        shift
-        ;;
-      --agent-vault-port)
-        assert_not_empty "$key" "$2"
-        agent_vault_port="$2"
-        shift
-        ;;
-      --agent-ca-cert_file)
-        assert_not_empty "$key" "$2"
-        agent_ca_cert_file="$2"
-        shift
-        ;;
-      --agent-client-cert-file)
-        assert_not_empty "$key" "$2"
-        agent_client_cert_file="$2"
-        shift
-        ;;
-      --agent-client-key-file)
-        assert_not_empty "$key" "$2"
-        agent_client_key_file="$2"
-        shift
-        ;;
-      --agent-auth-mount-path)
-        assert_not_empty "$key" "$2"
-        agent_auth_mount_path="$2"
-        shift
-        ;;
-      --agent-auth-type)
-        agent_auth_type="$2"
-        shift
-        ;;
-      --agent-auth-role)
-        agent_auth_role="$2"
-        shift
-        ;;
-      --enable-auto-unseal)
-        enable_auto_unseal="true"
-        ;;
-      --auto-unseal-kms-key-id)
-        auto_unseal_kms_key_id="$2"
-        shift
-        ;;
-      --auto-unseal-kms-key-region)
-        auto_unseal_kms_key_region="$2"
-        shift
-        ;;
-      --auto-unseal-endpoint)
-        auto_unseal_endpoint="$2"
-        shift
-        ;;
-      --help)
-        print_usage
-        exit
-        ;;
-      *)
-        log_error "Unrecognized argument: $key"
-        print_usage
-        exit 1
-        ;;
+    --tls-cert-file)
+      tls_cert_file="$2"
+      shift
+      ;;
+    --tls-key-file)
+      tls_key_file="$2"
+      shift
+      ;;
+    --port)
+      assert_not_empty "$key" "$2"
+      port="$2"
+      shift
+      ;;
+    --cluster-port)
+      assert_not_empty "$key" "$2"
+      cluster_port="$2"
+      shift
+      ;;
+    --config-dir)
+      assert_not_empty "$key" "$2"
+      config_dir="$2"
+      shift
+      ;;
+    --api-addr)
+      assert_not_empty "$key" "$2"
+      api_addr="$2"
+      shift
+      ;;
+    --bin-dir)
+      assert_not_empty "$key" "$2"
+      bin_dir="$2"
+      shift
+      ;;
+    --log-level)
+      assert_not_empty "$key" "$2"
+      log_level="$2"
+      shift
+      ;;
+    --systemd-stdout)
+      assert_not_empty "$key" "$2"
+      systemd_stdout="$2"
+      shift
+      ;;
+    --systemd-stderr)
+      assert_not_empty "$key" "$2"
+      systemd_stderr="$2"
+      shift
+      ;;
+    --user)
+      assert_not_empty "$key" "$2"
+      user="$2"
+      shift
+      ;;
+    --skip-vault-config)
+      skip_vault_config="true"
+      ;;
+    --enable-s3-backend)
+      enable_s3_backend="true"
+      ;;
+    --s3-bucket)
+      s3_bucket="$2"
+      shift
+      ;;
+    --s3-bucket-path)
+      s3_bucket_path="$2"
+      shift
+      ;;
+    --s3-bucket-region)
+      s3_bucket_region="$2"
+      shift
+      ;;
+    --agent)
+      agent="true"
+      ;;
+    --agent-vault-address)
+      assert_not_empty "$key" "$2"
+      agent_vault_address="$2"
+      shift
+      ;;
+    --agent-vault-port)
+      assert_not_empty "$key" "$2"
+      agent_vault_port="$2"
+      shift
+      ;;
+    --agent-ca-cert_file)
+      assert_not_empty "$key" "$2"
+      agent_ca_cert_file="$2"
+      shift
+      ;;
+    --agent-client-cert-file)
+      assert_not_empty "$key" "$2"
+      agent_client_cert_file="$2"
+      shift
+      ;;
+    --agent-client-key-file)
+      assert_not_empty "$key" "$2"
+      agent_client_key_file="$2"
+      shift
+      ;;
+    --agent-auth-mount-path)
+      assert_not_empty "$key" "$2"
+      agent_auth_mount_path="$2"
+      shift
+      ;;
+    --agent-auth-type)
+      agent_auth_type="$2"
+      shift
+      ;;
+    --agent-auth-role)
+      agent_auth_role="$2"
+      shift
+      ;;
+    --enable-auto-unseal)
+      enable_auto_unseal="true"
+      ;;
+    --auto-unseal-kms-key-id)
+      auto_unseal_kms_key_id="$2"
+      shift
+      ;;
+    --auto-unseal-kms-key-region)
+      auto_unseal_kms_key_region="$2"
+      shift
+      ;;
+    --auto-unseal-endpoint)
+      auto_unseal_endpoint="$2"
+      shift
+      ;;
+    --tls-cipher-suites)
+      tls_cipher_suites="$2"
+      shift
+      ;;
+    --help)
+      print_usage
+      exit
+      ;;
+    *)
+      log_error "Unrecognized argument: $key"
+      print_usage
+      exit 1
+      ;;
     esac
 
     shift
@@ -623,7 +642,7 @@ function run {
   fi
 
   if [[ -z "$cluster_port" ]]; then
-    cluster_port=$(( $port + 1 ))
+    cluster_port=$(($port + 1))
   fi
 
   if [[ -z "$api_addr" ]]; then
@@ -669,7 +688,8 @@ function run {
         "$enable_auto_unseal" \
         "$auto_unseal_kms_key_id" \
         "$auto_unseal_kms_key_region" \
-        "$auto_unseal_endpoint"
+        "$auto_unseal_endpoint" \
+        "$tls_cipher_suites"
     fi
   fi
 
